function tag(name: string, inputType?: string) {
    const t = $(document.createElement(name))
    if (inputType)
        t.prop("type", inputType)
    return t;
}

export const div = () => tag("div")
export const button = () => tag("button")
export const img = () => tag("img")
export const span = () => tag("span")
export const script = () => tag("script")
export const p = () => tag("p")
export const br = () => tag("br")
export const strong = () => tag("strong")
export const a = () => tag("a")
export const h1 = () => tag("h1")
export const h2 = () => tag("h2")
export const h3 = () => tag("h3")
export const h4 = () => tag("h4")
export const hr = () => tag("hr")
export const ul = () => tag("ul")
export const li = () => tag("li")
export const select = () => tag("select")
export const option = () => tag("option")
export const table = () => tag("table")
export const th = () => tag("th")
export const tr = () => tag("tr")
export const td = () => tag("td")
export const label = () => tag("label")
export const itext = () => tag("input", "text")
export const iemail = () => tag("input", "mail")
export const ipassword = () => tag("input", "password")
export const inumber = () => tag("input", "number")
export const ifile = () => tag("input", "file")
export const isubmit = () => tag("input", "submit")
export const icheckbox = () => tag("input", "checkbox")
export const iradio = () => tag("input", "radio")
export const itextarea = () => tag("textarea")